name: Frontend Build PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".github/agents/**"
      - "backend/**"

permissions:
  contents: read

jobs:
  verify-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build docker image and push
        id: build_image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          build-args: |
            NEXT_PUBLIC_BASE_PATH=/beta
            NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN=phc_7SSwxHEWr80MdWwKQfAbFKhvn3R1wvr1vK9ndObb21T
            NEXT_PUBLIC_POSTHOG_HOST=https://eu.i.posthog.com
            RUN_VERIFICATIONS=true
